# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: |
          npm install
          npm run build:library
          rm ./git-version-workflow
          echo $(cat ./version) > ./git-version-workflow
      - run: npm publish ./publish
      - run: git config --global user.email "mjoaopedro61@gmail.com"
      - run: git config --global user.name "JoaoPedro61"
      - run: git add .
      - run: git commit -m "GENERATE BUILD FROM WORKFLOW"
      - run: git push
        env:
           NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
