# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - run: npm install
      - run: npm run build
      - run: rm -rf link/*
      - run: cp publish-doc/* ./link/
      - run: cd ./link/
      - run: git add .
      - run: rm ./../git-version-workflow
      - run: echo $(cat ./../version) > ./../git-version-workflow
      - run: cp ./../git-version-workflow . 
      - run: VERSION=$(cat ./../version) && git commit -m "version/$VERSION"
      - run: git push origin HEAD:master
      - run: cd ./../

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
          registry-url: https://npm.pkg.github.com/
      - run: npm publish ./publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
