# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
          token: '${{ secrets.GITHUB_PAT }}'

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - run: |
          npm install
          npm run build
          rm -rf link/*
          cp publish-doc/* ./link/
          cd ./link/
          git add .
          rm ./../git-version-workflow
          echo $(cat ./../version) > ./../git-version-workflow
          cp ./../git-version-workflow . 
          VERSION=$(cat ./../version) && git commit -m "version/$VERSION"
          git push origin HEAD:master
          cd ./../

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
          registry-url: https://npm.pkg.github.com/
      - run: npm publish ./publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
